name: flutter_2023_it4785
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.0
  flutter_telephony_info: ^0.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.5.0
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
      - assets/data/
      - assets/images/
